/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t _3dshader_shbin_shbin[];
extern const uint8_t _3dshader_shbin_shbin_end[];
#if __cplusplus >= 201103L
static constexpr size_t _3dshader_shbin_shbin_size=320;
#else
static const size_t _3dshader_shbin_shbin_size=320;
#endif
